"use strict";
let m = 40;
let n = 80;
let o = 10;
console.log(m + n + o);
console.log(m - m - 0);
console.log(n * m * o);
console.log(n / m / o);
console.log(n % m % o);
//boolean data type;
console.log(true);
console.log(false);
console.log(2 === 2);
